### PR TITLE
📝  Create CITATION.cff

### PR DESCRIPTION
**Pull request by elisabettai**
Add a citation file, so it can be used to cite the "oSPARC API" e.g. in scientific papers

### CODE REVIEW

**Review by pcrespov — APPROVED** [review]
cool. thx!

**Review by wvangeit — APPROVED** [review]
Nice.
you might also consider creating a DOI with zenodo, e.g.:

https://github.com/BlueBrain/BluePyMM/blob/master/.zenodo.json
https://zenodo.org/records/10512287

**Comment by elisabettai** [comment]
> Nice. you might also consider creating a DOI with zenodo, e.g.:
> 
> https://github.com/BlueBrain/BluePyMM/blob/master/.zenodo.json https://zenodo.org/records/10512287

Thanks @wvangeit. Yeah, I was thinking about that as well. Especially because some journal allow citing software/code only if they have a DOI. Let's see. In your BluePyMM example, you created the entry in Zenodo, manually, right?

**Comment by wvangeit** [comment]
@elisabettai No, it's automatic. Whenever there is a commit in master, there is a new release generated (https://github.com/BlueBrain/BluePyMM/blob/3d21d31e761e5b32c8ad9e25c5d839ce2bd79122/.github/workflows/build.yml#L48)
Zenodo monitors releases in the repo, and mints a new DOI / page for each release.

**Comment by wvangeit** [comment]
But of course, it is possible to also generate a page manually. There is also a specific DOI for all versions:
Screenshot 2024-05-31 at 10 12 13

**Pull request merged**
