### PR TITLE
📝 Expanding doc to easier find doc for api versions

### PR DESCRIPTION
**Pull request by wvangeit**
## What do these changes do?

Remove direct tutorial link from main readme, since it doesn't work.
Mention direct links to API versions in doc.

## Related issue/s

- #76 

## How to test

Look at new doc. Screenshot:

Screenshot 2023-10-19 at 10 48 05

### CODE REVIEW

**Comment by wvangeit** [comment]
Thx @pcrespov , I forgot to assign/put milestone.
Btw, I saw that when you did that, it triggered a ci run. It seems this is caused by:
https://github.com/ITISFoundation/osparc-simcore-clients/blob/3d27841da013554823476ea761e0e15f7a00c2df/.github/workflows/publish-python-client.yml#L11

Do we really need that, it seems a bit of a waste of ci runners?

**Review by pcrespov — APPROVED** [review]
I took the liberty to assign the PR  to you and add the milestone. I also added `-`  to the related issue. This way the title is rendered. BTW see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword to automatically close related issues.
These are standard practices that we follow to keep track of the PRs. 
thx

**Comment by pcrespov** [comment]
> Do we really need that, it seems a bit of a waste of ci runners?
@wvangeit I agree but please double check with @bisgaard-itis first. He added that and might have a different opinion

**Comment by bisgaard-itis** [comment]
> Thx @pcrespov , I forgot to assign/put milestone. Btw, I saw that when you did that, it triggered a ci run. It seems this is caused by:
> 
> https://github.com/ITISFoundation/osparc-simcore-clients/blob/3d27841da013554823476ea761e0e15f7a00c2df/.github/workflows/publish-python-client.yml#L11
> 
> Do we really need that, it seems a bit of a waste of ci runners?

Yep, I agree. I guess I added that when I was setting up the building of the website and modifying this workflow for debugging. I guess this workflow should actually only be triggered when something is pushed to `master`. Agree @wvangeit?

**Review by bisgaard-itis — APPROVED** [review]
Looks good. Thanks for the effort

**Pull request merged**
